<?php
/**
 * IMAGE SCALE HUB - WEB INSTALLER
 * 
 * This PHP installer provides a GUI for setting up the application.
 * Upload this to your server and access it via browser.
 * Fully customizable - enter your own app name!
 * 
 * Requirements:
 * - PHP 7.4+
 * - Shell access (exec)
 * - Root/sudo access
 */

session_start();

// Security: Only allow installation once
$lockFile = __DIR__ . '/.installed';
$isInstalled = file_exists($lockFile);

// Handle form submission
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($step) {
        case 1: // System check - just proceed
            header('Location: ?step=2');
            exit;
            
        case 2: // App name & Database config
            $_SESSION['config'] = [
                'app_name' => $_POST['app_name'] ?: 'Image Scale Hub',
                'db_type' => $_POST['db_type'],
                'db_host' => $_POST['db_host'] ?? '',
                'db_port' => $_POST['db_port'] ?? '',
                'db_name' => $_POST['db_name'] ?? '',
                'db_user' => $_POST['db_user'] ?? '',
                'db_pass' => $_POST['db_pass'] ?? '',
            ];
            header('Location: ?step=3');
            exit;
            
        case 3: // Domain & SSL
            $_SESSION['config']['domain'] = $_POST['domain'] ?? '';
            $_SESSION['config']['use_ssl'] = isset($_POST['use_ssl']);
            $_SESSION['config']['ssl_email'] = $_POST['ssl_email'] ?? '';
            header('Location: ?step=4');
            exit;
            
        case 4: // Admin account
            $_SESSION['config']['admin_user'] = $_POST['admin_user'];
            $_SESSION['config']['admin_pass'] = $_POST['admin_pass'];
            $_SESSION['config']['admin_email'] = $_POST['admin_email'];
            $_SESSION['config']['site_name'] = $_POST['site_name'];
            header('Location: ?step=5');
            exit;
            
        case 5: // Install
            $config = $_SESSION['config'];
            
            // Generate .env file content
            $secretKey = bin2hex(random_bytes(32));
            
            // Build database URL
            if ($config['db_type'] === 'sqlite') {
                $dbUrl = 'sqlite:////app/data/users.db';
            } elseif ($config['db_type'] === 'mysql') {
                $dbUrl = "mysql+pymysql://{$config['db_user']}:{$config['db_pass']}@{$config['db_host']}:{$config['db_port']}/{$config['db_name']}";
            } else {
                $dbUrl = "postgresql://{$config['db_user']}:{$config['db_pass']}@{$config['db_host']}:{$config['db_port']}/{$config['db_name']}";
            }
            
            $envContent = "# {$config['app_name']} Configuration
# Generated by Web Installer on " . date('Y-m-d H:i:s') . "

SECRET_KEY={$secretKey}
APP_NAME={$config['app_name']}
APP_VERSION=1.0.0
FLASK_CONFIG=production

# Database
DATABASE_URL={$dbUrl}

# Domain & SSL
CUSTOM_DOMAIN={$config['domain']}
FORCE_HTTPS=" . ($config['use_ssl'] ? 'true' : 'false') . "

# Security
SESSION_TIMEOUT=1800
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION=900

# Storage
MAX_FILE_SIZE=10485760
DEFAULT_STORAGE_LIMIT_MB=100
ALLOWED_EXTENSIONS=jpg,jpeg,png,webp,gif,bmp

# Features
ENABLE_REGISTRATION=false
";
            
            // Save config for display
            $_SESSION['env_content'] = $envContent;
            $_SESSION['install_config'] = $config;
            
            header('Location: ?step=6');
            exit;
    }
}

// Check system requirements
function checkRequirements() {
    $checks = [];
    
    // PHP Version
    $checks['php_version'] = [
        'name' => 'PHP Version (7.4+)',
        'status' => version_compare(PHP_VERSION, '7.4.0', '>='),
        'value' => PHP_VERSION
    ];
    
    // Shell exec
    $checks['shell_exec'] = [
        'name' => 'Shell Access',
        'status' => function_exists('exec') && !in_array('exec', explode(',', ini_get('disable_functions'))),
        'value' => function_exists('exec') ? 'Available' : 'Disabled'
    ];
    
    // Docker
    $dockerVersion = @shell_exec('docker --version 2>&1');
    $checks['docker'] = [
        'name' => 'Docker',
        'status' => strpos($dockerVersion, 'Docker version') !== false,
        'value' => $dockerVersion ? trim($dockerVersion) : 'Not installed'
    ];
    
    // Nginx
    $nginxVersion = @shell_exec('nginx -v 2>&1');
    $checks['nginx'] = [
        'name' => 'Nginx (optional)',
        'status' => strpos($nginxVersion, 'nginx') !== false,
        'value' => $nginxVersion ? trim($nginxVersion) : 'Not installed',
        'optional' => true
    ];
    
    // Certbot
    $certbotVersion = @shell_exec('certbot --version 2>&1');
    $checks['certbot'] = [
        'name' => 'Certbot (optional)',
        'status' => strpos($certbotVersion, 'certbot') !== false,
        'value' => $certbotVersion ? trim($certbotVersion) : 'Not installed',
        'optional' => true
    ];
    
    // Write permissions
    $checks['writable'] = [
        'name' => 'Write Permissions',
        'status' => is_writable(__DIR__),
        'value' => is_writable(__DIR__) ? 'Writable' : 'Not writable'
    ];
    
    return $checks;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Scale Hub - Installer</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            padding: 40px 20px;
            color: #333;
        }
        .installer {
            max-width: 700px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 { font-size: 28px; margin-bottom: 10px; }
        .header p { opacity: 0.9; }
        
        .steps {
            display: flex;
            background: #f8f9fa;
            padding: 15px;
            justify-content: center;
            gap: 10px;
            flex-wrap: wrap;
        }
        .step-indicator {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: #e0e0e0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 14px;
            color: #666;
        }
        .step-indicator.active {
            background: #667eea;
            color: white;
        }
        .step-indicator.done {
            background: #27ae60;
            color: white;
        }
        
        .content { padding: 30px; }
        
        h2 { color: #1a1a2e; margin-bottom: 20px; font-size: 22px; }
        
        .form-group { margin-bottom: 20px; }
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #374151;
        }
        .form-group input, .form-group select {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            font-size: 15px;
            transition: border-color 0.2s;
        }
        .form-group input:focus, .form-group select:focus {
            outline: none;
            border-color: #667eea;
        }
        .form-group small {
            display: block;
            margin-top: 5px;
            color: #6b7280;
            font-size: 13px;
        }
        
        .form-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
        }
        
        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .checkbox-group input { width: auto; }
        
        .btn {
            padding: 14px 30px;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
        }
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
        }
        .btn-secondary {
            background: #e5e7eb;
            color: #374151;
        }
        
        .buttons {
            display: flex;
            justify-content: space-between;
            margin-top: 30px;
        }
        
        .check-list { list-style: none; }
        .check-list li {
            padding: 12px 15px;
            border-radius: 8px;
            margin-bottom: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .check-list li.pass { background: #d1fae5; }
        .check-list li.fail { background: #fee2e2; }
        .check-list li.warn { background: #fef3c7; }
        
        .status-icon {
            width: 24px;
            height: 24px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 14px;
        }
        .status-icon.pass { background: #10b981; color: white; }
        .status-icon.fail { background: #ef4444; color: white; }
        .status-icon.warn { background: #f59e0b; color: white; }
        
        .db-options { display: none; }
        .db-options.active { display: block; }
        
        .code-block {
            background: #1e293b;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 8px;
            font-family: monospace;
            font-size: 13px;
            overflow-x: auto;
            white-space: pre-wrap;
            margin: 20px 0;
        }
        
        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .alert-info { background: #dbeafe; color: #1e40af; }
        .alert-success { background: #d1fae5; color: #065f46; }
        .alert-warning { background: #fef3c7; color: #92400e; }
        
        .install-commands {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .install-commands h4 { margin-bottom: 15px; }
        .install-commands code {
            display: block;
            background: #1e293b;
            color: #10b981;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 10px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="installer">
        <div class="header">
            <h1>🖼️ Image Scale Hub</h1>
            <p>Installation Wizard</p>
        </div>
        
        <div class="steps">
            <?php for ($i = 1; $i <= 6; $i++): ?>
                <div class="step-indicator <?= $i < $step ? 'done' : ($i === $step ? 'active' : '') ?>">
                    <?= $i < $step ? '✓' : $i ?>
                </div>
            <?php endfor; ?>
        </div>
        
        <div class="content">
            <?php if ($isInstalled && $step < 6): ?>
                <div class="alert alert-warning">
                    ⚠️ Installation has already been completed. Delete the <code>.installed</code> file to reinstall.
                </div>
            <?php endif; ?>
            
            <?php if ($step === 1): ?>
                <!-- Step 1: System Check -->
                <h2>📋 System Requirements</h2>
                <p style="margin-bottom: 20px; color: #6b7280;">Checking if your server meets the requirements...</p>
                
                <?php $checks = checkRequirements(); $allPass = true; ?>
                <ul class="check-list">
                    <?php foreach ($checks as $check): ?>
                        <?php 
                        $status = $check['status'] ? 'pass' : (isset($check['optional']) ? 'warn' : 'fail');
                        if (!$check['status'] && !isset($check['optional'])) $allPass = false;
                        ?>
                        <li class="<?= $status ?>">
                            <div>
                                <strong><?= $check['name'] ?></strong>
                                <small style="display: block; color: #666;"><?= $check['value'] ?></small>
                            </div>
                            <div class="status-icon <?= $status ?>">
                                <?= $status === 'pass' ? '✓' : ($status === 'warn' ? '!' : '✗') ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
                
                <form method="POST">
                    <div class="buttons">
                        <div></div>
                        <button type="submit" class="btn btn-primary" <?= !$allPass ? 'disabled' : '' ?>>
                            Continue →
                        </button>
                    </div>
                </form>
                
            <?php elseif ($step === 2): ?>
                <!-- Step 2: App Name & Database -->
                <h2>🎨 Branding & Database</h2>
                
                <form method="POST">
                    <div class="form-group">
                        <label>Your App Name</label>
                        <input type="text" name="app_name" placeholder="My Image Tool" value="">
                        <small>This will be displayed throughout the app. Leave blank for "Image Scale Hub"</small>
                    </div>
                    
                    <hr style="margin: 20px 0; border: none; border-top: 1px solid #e5e7eb;">
                    
                    <div class="form-group">
                        <label>Database Type</label>
                        <select name="db_type" id="dbType" onchange="toggleDbOptions()">
                            <option value="sqlite">SQLite (Recommended for single server)</option>
                            <option value="mysql">MySQL (Recommended for production)</option>
                            <option value="postgresql">PostgreSQL (Enterprise)</option>
                        </select>
                    </div>
                    
                    <div id="dbOptions" class="db-options">
                        <div class="form-row">
                            <div class="form-group">
                                <label>Host</label>
                                <input type="text" name="db_host" value="localhost">
                            </div>
                            <div class="form-group">
                                <label>Port</label>
                                <input type="text" name="db_port" id="dbPort" value="3306">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Database Name</label>
                            <input type="text" name="db_name" value="image_resizer">
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" name="db_user">
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="db_pass">
                            </div>
                        </div>
                    </div>
                    
                    <div class="buttons">
                        <a href="?step=1" class="btn btn-secondary">← Back</a>
                        <button type="submit" class="btn btn-primary">Continue →</button>
                    </div>
                </form>
                
                <script>
                function toggleDbOptions() {
                    const type = document.getElementById('dbType').value;
                    const options = document.getElementById('dbOptions');
                    const port = document.getElementById('dbPort');
                    
                    if (type === 'sqlite') {
                        options.classList.remove('active');
                    } else {
                        options.classList.add('active');
                        port.value = type === 'mysql' ? '3306' : '5432';
                    }
                }
                </script>
                
            <?php elseif ($step === 3): ?>
                <!-- Step 3: Domain & SSL -->
                <h2>🌐 Domain & SSL</h2>
                
                <form method="POST">
                    <div class="form-group">
                        <label>Domain Name (optional)</label>
                        <input type="text" name="domain" placeholder="images.example.com">
                        <small>Leave empty to use IP address only</small>
                    </div>
                    
                    <div class="form-group checkbox-group">
                        <input type="checkbox" name="use_ssl" id="useSSL" onchange="toggleSSLEmail()">
                        <label for="useSSL" style="margin: 0;">Enable Free SSL Certificate (Let's Encrypt)</label>
                    </div>
                    
                    <div class="form-group" id="sslEmail" style="display: none;">
                        <label>Email for SSL Certificate</label>
                        <input type="email" name="ssl_email" placeholder="admin@example.com">
                        <small>Required for SSL certificate registration</small>
                    </div>
                    
                    <div class="alert alert-info">
                        💡 <strong>Note:</strong> For SSL to work, your domain must already point to this server's IP address.
                    </div>
                    
                    <div class="buttons">
                        <a href="?step=2" class="btn btn-secondary">← Back</a>
                        <button type="submit" class="btn btn-primary">Continue →</button>
                    </div>
                </form>
                
                <script>
                function toggleSSLEmail() {
                    document.getElementById('sslEmail').style.display = 
                        document.getElementById('useSSL').checked ? 'block' : 'none';
                }
                </script>
                
            <?php elseif ($step === 4): ?>
                <!-- Step 4: Admin Account -->
                <h2>👤 Admin Account</h2>
                
                <form method="POST">
                    <div class="form-group">
                        <label>Site Name</label>
                        <input type="text" name="site_name" value="Scorpio Image Resizer" required>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label>Admin Username</label>
                            <input type="text" name="admin_user" value="admin" required>
                        </div>
                        <div class="form-group">
                            <label>Admin Email</label>
                            <input type="email" name="admin_email" required>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label>Admin Password</label>
                        <input type="password" name="admin_pass" required minlength="8">
                        <small>Minimum 8 characters</small>
                    </div>
                    
                    <div class="buttons">
                        <a href="?step=3" class="btn btn-secondary">← Back</a>
                        <button type="submit" class="btn btn-primary">Continue →</button>
                    </div>
                </form>
                
            <?php elseif ($step === 5): ?>
                <!-- Step 5: Review -->
                <h2>📝 Review Configuration</h2>
                
                <?php $config = $_SESSION['config'] ?? []; ?>
                
                <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
                    <h4 style="margin-bottom: 15px;">Configuration Summary</h4>
                    <table style="width: 100%;">
                        <tr><td><strong>Database:</strong></td><td><?= ucfirst($config['db_type'] ?? 'sqlite') ?></td></tr>
                        <tr><td><strong>Domain:</strong></td><td><?= $config['domain'] ?: 'None (IP only)' ?></td></tr>
                        <tr><td><strong>SSL:</strong></td><td><?= ($config['use_ssl'] ?? false) ? 'Yes' : 'No' ?></td></tr>
                        <tr><td><strong>Site Name:</strong></td><td><?= $config['site_name'] ?? '' ?></td></tr>
                        <tr><td><strong>Admin User:</strong></td><td><?= $config['admin_user'] ?? '' ?></td></tr>
                    </table>
                </div>
                
                <form method="POST">
                    <div class="buttons">
                        <a href="?step=4" class="btn btn-secondary">← Back</a>
                        <button type="submit" class="btn btn-primary">🚀 Generate Configuration</button>
                    </div>
                </form>
                
            <?php elseif ($step === 6): ?>
                <!-- Step 6: Complete -->
                <h2>✅ Configuration Generated!</h2>
                
                <div class="alert alert-success">
                    Your configuration has been generated. Follow the steps below to complete installation.
                </div>
                
                <h4>1. Save this .env file to your server:</h4>
                <div class="code-block"><?= htmlspecialchars($_SESSION['env_content'] ?? '') ?></div>
                
                <h4>2. Run these commands on your server:</h4>
                <div class="install-commands">
                    <code>cd /opt/scorpio-image-resizer</code>
                    <code>nano .env  # Paste the config above</code>
                    <code>docker-compose up -d</code>
                    <?php if ($_SESSION['install_config']['use_ssl'] ?? false): ?>
                    <code>certbot --nginx -d <?= $_SESSION['install_config']['domain'] ?></code>
                    <?php endif; ?>
                </div>
                
                <h4>3. Access your application:</h4>
                <p style="margin: 15px 0;">
                    <?php 
                    $config = $_SESSION['install_config'] ?? [];
                    $url = $config['domain'] ? 
                        (($config['use_ssl'] ?? false) ? 'https://' : 'http://') . $config['domain'] : 
                        'http://YOUR_SERVER_IP:5000';
                    ?>
                    <a href="<?= $url ?>" target="_blank" class="btn btn-primary"><?= $url ?></a>
                </p>
                
                <div class="alert alert-warning" style="margin-top: 20px;">
                    ⚠️ <strong>Security:</strong> Delete this installer directory after installation!
                </div>
                
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
